branch-defaults:
  master:
    environment: eb--secret--library
environment-defaults:
  secret--library:
    branch: null
    repository: null
global:
  application_name: "\uBE44\uBC00\uC11C\uC7AC"
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Node.js
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
